-- Typed models for the RestCountries SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class All
---@field altSpellings? table
---@field area? number
---@field borders? table
---@field capital? table
---@field capitalInfo? table
---@field car? table
---@field cca2? string
---@field cca3? string
---@field ccn3? string
---@field cioc? string
---@field coatOfArms? table
---@field continents? table
---@field currencies? table
---@field demonyms? table
---@field fifa? string
---@field flag? string
---@field flags? table
---@field gini? table
---@field idd? table
---@field independent? boolean
---@field landlocked? boolean
---@field languages? table
---@field latlng? table
---@field maps? table
---@field name? table
---@field population? number
---@field postalCode? table
---@field region? string
---@field startOfWeek? string
---@field status? string
---@field subregion? string
---@field timezones? table
---@field tld? table
---@field translations? table
---@field unMember? boolean

---@class AllListMatch
---@field field? string

---@class Alpha
---@field altSpellings? table
---@field area? number
---@field borders? table
---@field capital? table
---@field capitalInfo? table
---@field car? table
---@field cca2? string
---@field cca3? string
---@field ccn3? string
---@field cioc? string
---@field coatOfArms? table
---@field continents? table
---@field currencies? table
---@field demonyms? table
---@field fifa? string
---@field flag? string
---@field flags? table
---@field gini? table
---@field id? string
---@field idd? table
---@field independent? boolean
---@field landlocked? boolean
---@field languages? table
---@field latlng? table
---@field maps? table
---@field name? table
---@field population? number
---@field postalCode? table
---@field region? string
---@field startOfWeek? string
---@field status? string
---@field subregion? string
---@field timezones? table
---@field tld? table
---@field translations? table
---@field unMember? boolean

---@class AlphaLoadMatch
---@field id string
---@field field? string

---@class Capital
---@field altSpellings? table
---@field area? number
---@field borders? table
---@field capital? table
---@field capitalInfo? table
---@field car? table
---@field cca2? string
---@field cca3? string
---@field ccn3? string
---@field cioc? string
---@field coatOfArms? table
---@field continents? table
---@field currencies? table
---@field demonyms? table
---@field fifa? string
---@field flag? string
---@field flags? table
---@field gini? table
---@field id? string
---@field idd? table
---@field independent? boolean
---@field landlocked? boolean
---@field languages? table
---@field latlng? table
---@field maps? table
---@field name? table
---@field population? number
---@field postalCode? table
---@field region? string
---@field startOfWeek? string
---@field status? string
---@field subregion? string
---@field timezones? table
---@field tld? table
---@field translations? table
---@field unMember? boolean

---@class CapitalLoadMatch
---@field id string
---@field field? string

---@class Name
---@field altSpellings? table
---@field area? number
---@field borders? table
---@field capital? table
---@field capitalInfo? table
---@field car? table
---@field cca2? string
---@field cca3? string
---@field ccn3? string
---@field cioc? string
---@field coatOfArms? table
---@field continents? table
---@field currencies? table
---@field demonyms? table
---@field fifa? string
---@field flag? string
---@field flags? table
---@field gini? table
---@field id? string
---@field idd? table
---@field independent? boolean
---@field landlocked? boolean
---@field languages? table
---@field latlng? table
---@field maps? table
---@field name? table
---@field population? number
---@field postalCode? table
---@field region? string
---@field startOfWeek? string
---@field status? string
---@field subregion? string
---@field timezones? table
---@field tld? table
---@field translations? table
---@field unMember? boolean

---@class NameLoadMatch
---@field id string
---@field field? string
---@field full_text? boolean

local M = {}

return M
