# RestCountries SDK configuration


def make_config():
    return {
        "main": {
            "name": "RestCountries",
        },
        "feature": {
            "test": {
        "options": {
          "active": False,
        },
      },
        },
        "options": {
            "base": "https://restcountries.com/v3.1",
            "auth": {
                "prefix": "Bearer",
            },
            "headers": {
        "content-type": "application/json",
      },
            "entity": {
                "all": {},
                "alpha": {},
                "capital": {},
                "name": {},
            },
        },
        "entity": {
      "all": {
        "fields": [
          {
            "name": "alt_spelling",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 0,
          },
          {
            "name": "area",
            "req": False,
            "type": "`$NUMBER`",
            "active": True,
            "index$": 1,
          },
          {
            "name": "border",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 2,
          },
          {
            "name": "capital",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 3,
          },
          {
            "name": "capital_info",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 4,
          },
          {
            "name": "car",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 5,
          },
          {
            "name": "cca2",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 6,
          },
          {
            "name": "cca3",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 7,
          },
          {
            "name": "ccn3",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 8,
          },
          {
            "name": "cioc",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 9,
          },
          {
            "name": "coat_of_arm",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 10,
          },
          {
            "name": "continent",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 11,
          },
          {
            "name": "currency",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 12,
          },
          {
            "name": "demonym",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 13,
          },
          {
            "name": "fifa",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 14,
          },
          {
            "name": "flag",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 15,
          },
          {
            "name": "gini",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 16,
          },
          {
            "name": "idd",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 17,
          },
          {
            "name": "independent",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 18,
          },
          {
            "name": "landlocked",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 19,
          },
          {
            "name": "language",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 20,
          },
          {
            "name": "latlng",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 21,
          },
          {
            "name": "map",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 22,
          },
          {
            "name": "name",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 23,
          },
          {
            "name": "population",
            "req": False,
            "type": "`$INTEGER`",
            "active": True,
            "index$": 24,
          },
          {
            "name": "postal_code",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 25,
          },
          {
            "name": "region",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 26,
          },
          {
            "name": "start_of_week",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 27,
          },
          {
            "name": "status",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 28,
          },
          {
            "name": "subregion",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 29,
          },
          {
            "name": "timezone",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 30,
          },
          {
            "name": "tld",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 31,
          },
          {
            "name": "translation",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 32,
          },
          {
            "name": "un_member",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 33,
          },
        ],
        "name": "all",
        "op": {
          "list": {
            "name": "list",
            "points": [
              {
                "args": {
                  "query": [
                    {
                      "example": "name,capital,population",
                      "kind": "query",
                      "name": "field",
                      "orig": "field",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/all",
                "parts": [
                  "all",
                ],
                "select": {
                  "exist": [
                    "field",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "active": True,
                "index$": 0,
              },
            ],
            "input": "data",
            "key$": "list",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "alpha": {
        "fields": [
          {
            "name": "alt_spelling",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 0,
          },
          {
            "name": "area",
            "req": False,
            "type": "`$NUMBER`",
            "active": True,
            "index$": 1,
          },
          {
            "name": "border",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 2,
          },
          {
            "name": "capital",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 3,
          },
          {
            "name": "capital_info",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 4,
          },
          {
            "name": "car",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 5,
          },
          {
            "name": "cca2",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 6,
          },
          {
            "name": "cca3",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 7,
          },
          {
            "name": "ccn3",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 8,
          },
          {
            "name": "cioc",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 9,
          },
          {
            "name": "coat_of_arm",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 10,
          },
          {
            "name": "continent",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 11,
          },
          {
            "name": "currency",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 12,
          },
          {
            "name": "demonym",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 13,
          },
          {
            "name": "fifa",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 14,
          },
          {
            "name": "flag",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 15,
          },
          {
            "name": "gini",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 16,
          },
          {
            "name": "idd",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 17,
          },
          {
            "name": "independent",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 18,
          },
          {
            "name": "landlocked",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 19,
          },
          {
            "name": "language",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 20,
          },
          {
            "name": "latlng",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 21,
          },
          {
            "name": "map",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 22,
          },
          {
            "name": "name",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 23,
          },
          {
            "name": "population",
            "req": False,
            "type": "`$INTEGER`",
            "active": True,
            "index$": 24,
          },
          {
            "name": "postal_code",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 25,
          },
          {
            "name": "region",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 26,
          },
          {
            "name": "start_of_week",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 27,
          },
          {
            "name": "status",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 28,
          },
          {
            "name": "subregion",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 29,
          },
          {
            "name": "timezone",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 30,
          },
          {
            "name": "tld",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 31,
          },
          {
            "name": "translation",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 32,
          },
          {
            "name": "un_member",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 33,
          },
        ],
        "name": "alpha",
        "op": {
          "load": {
            "name": "load",
            "points": [
              {
                "args": {
                  "params": [
                    {
                      "example": "de",
                      "kind": "param",
                      "name": "id",
                      "orig": "code",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                  "query": [
                    {
                      "kind": "query",
                      "name": "field",
                      "orig": "field",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/alpha/{code}",
                "parts": [
                  "alpha",
                  "{id}",
                ],
                "rename": {
                  "param": {
                    "code": "id",
                  },
                },
                "select": {
                  "exist": [
                    "field",
                    "id",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "active": True,
                "index$": 0,
              },
            ],
            "input": "data",
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "capital": {
        "fields": [
          {
            "name": "alt_spelling",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 0,
          },
          {
            "name": "area",
            "req": False,
            "type": "`$NUMBER`",
            "active": True,
            "index$": 1,
          },
          {
            "name": "border",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 2,
          },
          {
            "name": "capital",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 3,
          },
          {
            "name": "capital_info",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 4,
          },
          {
            "name": "car",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 5,
          },
          {
            "name": "cca2",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 6,
          },
          {
            "name": "cca3",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 7,
          },
          {
            "name": "ccn3",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 8,
          },
          {
            "name": "cioc",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 9,
          },
          {
            "name": "coat_of_arm",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 10,
          },
          {
            "name": "continent",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 11,
          },
          {
            "name": "currency",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 12,
          },
          {
            "name": "demonym",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 13,
          },
          {
            "name": "fifa",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 14,
          },
          {
            "name": "flag",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 15,
          },
          {
            "name": "gini",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 16,
          },
          {
            "name": "idd",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 17,
          },
          {
            "name": "independent",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 18,
          },
          {
            "name": "landlocked",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 19,
          },
          {
            "name": "language",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 20,
          },
          {
            "name": "latlng",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 21,
          },
          {
            "name": "map",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 22,
          },
          {
            "name": "name",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 23,
          },
          {
            "name": "population",
            "req": False,
            "type": "`$INTEGER`",
            "active": True,
            "index$": 24,
          },
          {
            "name": "postal_code",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 25,
          },
          {
            "name": "region",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 26,
          },
          {
            "name": "start_of_week",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 27,
          },
          {
            "name": "status",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 28,
          },
          {
            "name": "subregion",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 29,
          },
          {
            "name": "timezone",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 30,
          },
          {
            "name": "tld",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 31,
          },
          {
            "name": "translation",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 32,
          },
          {
            "name": "un_member",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 33,
          },
        ],
        "name": "capital",
        "op": {
          "load": {
            "name": "load",
            "points": [
              {
                "args": {
                  "params": [
                    {
                      "example": "berlin",
                      "kind": "param",
                      "name": "id",
                      "orig": "capital",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                  "query": [
                    {
                      "kind": "query",
                      "name": "field",
                      "orig": "field",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/capital/{capital}",
                "parts": [
                  "capital",
                  "{id}",
                ],
                "rename": {
                  "param": {
                    "capital": "id",
                  },
                },
                "select": {
                  "exist": [
                    "field",
                    "id",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "active": True,
                "index$": 0,
              },
            ],
            "input": "data",
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "name": {
        "fields": [
          {
            "name": "alt_spelling",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 0,
          },
          {
            "name": "area",
            "req": False,
            "type": "`$NUMBER`",
            "active": True,
            "index$": 1,
          },
          {
            "name": "border",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 2,
          },
          {
            "name": "capital",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 3,
          },
          {
            "name": "capital_info",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 4,
          },
          {
            "name": "car",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 5,
          },
          {
            "name": "cca2",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 6,
          },
          {
            "name": "cca3",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 7,
          },
          {
            "name": "ccn3",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 8,
          },
          {
            "name": "cioc",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 9,
          },
          {
            "name": "coat_of_arm",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 10,
          },
          {
            "name": "continent",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 11,
          },
          {
            "name": "currency",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 12,
          },
          {
            "name": "demonym",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 13,
          },
          {
            "name": "fifa",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 14,
          },
          {
            "name": "flag",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 15,
          },
          {
            "name": "gini",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 16,
          },
          {
            "name": "idd",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 17,
          },
          {
            "name": "independent",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 18,
          },
          {
            "name": "landlocked",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 19,
          },
          {
            "name": "language",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 20,
          },
          {
            "name": "latlng",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 21,
          },
          {
            "name": "map",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 22,
          },
          {
            "name": "name",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 23,
          },
          {
            "name": "population",
            "req": False,
            "type": "`$INTEGER`",
            "active": True,
            "index$": 24,
          },
          {
            "name": "postal_code",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 25,
          },
          {
            "name": "region",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 26,
          },
          {
            "name": "start_of_week",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 27,
          },
          {
            "name": "status",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 28,
          },
          {
            "name": "subregion",
            "req": False,
            "type": "`$STRING`",
            "active": True,
            "index$": 29,
          },
          {
            "name": "timezone",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 30,
          },
          {
            "name": "tld",
            "req": False,
            "type": "`$ARRAY`",
            "active": True,
            "index$": 31,
          },
          {
            "name": "translation",
            "req": False,
            "type": "`$OBJECT`",
            "active": True,
            "index$": 32,
          },
          {
            "name": "un_member",
            "req": False,
            "type": "`$BOOLEAN`",
            "active": True,
            "index$": 33,
          },
        ],
        "name": "name",
        "op": {
          "load": {
            "name": "load",
            "points": [
              {
                "args": {
                  "params": [
                    {
                      "example": "germany",
                      "kind": "param",
                      "name": "id",
                      "orig": "name",
                      "reqd": True,
                      "type": "`$STRING`",
                      "active": True,
                    },
                  ],
                  "query": [
                    {
                      "kind": "query",
                      "name": "field",
                      "orig": "field",
                      "reqd": False,
                      "type": "`$STRING`",
                      "active": True,
                    },
                    {
                      "example": False,
                      "kind": "query",
                      "name": "full_text",
                      "orig": "full_text",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                      "active": True,
                    },
                  ],
                },
                "method": "GET",
                "orig": "/name/{name}",
                "parts": [
                  "name",
                  "{id}",
                ],
                "rename": {
                  "param": {
                    "name": "id",
                  },
                },
                "select": {
                  "exist": [
                    "field",
                    "full_text",
                    "id",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "active": True,
                "index$": 0,
              },
            ],
            "input": "data",
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
    },
    }
