<?php
declare(strict_types=1);

// RestCountries SDK configuration

class RestCountriesConfig
{
    public static function make_config(): array
    {
        return [
            "main" => [
                "name" => "RestCountries",
            ],
            "feature" => [
                "test" => [
          'options' => [
            'active' => false,
          ],
        ],
            ],
            "options" => [
                "base" => "https://restcountries.com/v3.1",
                "headers" => [
          'content-type' => 'application/json',
        ],
                "entity" => [
                    "all" => [],
                    "alpha" => [],
                    "capital" => [],
                    "name" => [],
                ],
            ],
            "entity" => [
        'all' => [
          'fields' => [
            [
              'name' => 'alt_spelling',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 0,
            ],
            [
              'name' => 'area',
              'req' => false,
              'type' => '`$NUMBER`',
              'active' => true,
              'index$' => 1,
            ],
            [
              'name' => 'border',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 2,
            ],
            [
              'name' => 'capital',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 3,
            ],
            [
              'name' => 'capital_info',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 4,
            ],
            [
              'name' => 'car',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 5,
            ],
            [
              'name' => 'cca2',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 6,
            ],
            [
              'name' => 'cca3',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 7,
            ],
            [
              'name' => 'ccn3',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 8,
            ],
            [
              'name' => 'cioc',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 9,
            ],
            [
              'name' => 'coat_of_arm',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 10,
            ],
            [
              'name' => 'continent',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 11,
            ],
            [
              'name' => 'currency',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 12,
            ],
            [
              'name' => 'demonym',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 13,
            ],
            [
              'name' => 'fifa',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 14,
            ],
            [
              'name' => 'flag',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 15,
            ],
            [
              'name' => 'gini',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 16,
            ],
            [
              'name' => 'idd',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 17,
            ],
            [
              'name' => 'independent',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 18,
            ],
            [
              'name' => 'landlocked',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 19,
            ],
            [
              'name' => 'language',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 20,
            ],
            [
              'name' => 'latlng',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 21,
            ],
            [
              'name' => 'map',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 22,
            ],
            [
              'name' => 'name',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 23,
            ],
            [
              'name' => 'population',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 24,
            ],
            [
              'name' => 'postal_code',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 25,
            ],
            [
              'name' => 'region',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 26,
            ],
            [
              'name' => 'start_of_week',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 27,
            ],
            [
              'name' => 'status',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 28,
            ],
            [
              'name' => 'subregion',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 29,
            ],
            [
              'name' => 'timezone',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 30,
            ],
            [
              'name' => 'tld',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 31,
            ],
            [
              'name' => 'translation',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 32,
            ],
            [
              'name' => 'un_member',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 33,
            ],
          ],
          'name' => 'all',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'args' => [
                    'query' => [
                      [
                        'example' => 'name,capital,population',
                        'kind' => 'query',
                        'name' => 'field',
                        'orig' => 'field',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/all',
                  'parts' => [
                    'all',
                  ],
                  'select' => [
                    'exist' => [
                      'field',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'alpha' => [
          'fields' => [
            [
              'name' => 'alt_spelling',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 0,
            ],
            [
              'name' => 'area',
              'req' => false,
              'type' => '`$NUMBER`',
              'active' => true,
              'index$' => 1,
            ],
            [
              'name' => 'border',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 2,
            ],
            [
              'name' => 'capital',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 3,
            ],
            [
              'name' => 'capital_info',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 4,
            ],
            [
              'name' => 'car',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 5,
            ],
            [
              'name' => 'cca2',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 6,
            ],
            [
              'name' => 'cca3',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 7,
            ],
            [
              'name' => 'ccn3',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 8,
            ],
            [
              'name' => 'cioc',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 9,
            ],
            [
              'name' => 'coat_of_arm',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 10,
            ],
            [
              'name' => 'continent',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 11,
            ],
            [
              'name' => 'currency',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 12,
            ],
            [
              'name' => 'demonym',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 13,
            ],
            [
              'name' => 'fifa',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 14,
            ],
            [
              'name' => 'flag',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 15,
            ],
            [
              'name' => 'gini',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 16,
            ],
            [
              'name' => 'idd',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 17,
            ],
            [
              'name' => 'independent',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 18,
            ],
            [
              'name' => 'landlocked',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 19,
            ],
            [
              'name' => 'language',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 20,
            ],
            [
              'name' => 'latlng',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 21,
            ],
            [
              'name' => 'map',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 22,
            ],
            [
              'name' => 'name',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 23,
            ],
            [
              'name' => 'population',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 24,
            ],
            [
              'name' => 'postal_code',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 25,
            ],
            [
              'name' => 'region',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 26,
            ],
            [
              'name' => 'start_of_week',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 27,
            ],
            [
              'name' => 'status',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 28,
            ],
            [
              'name' => 'subregion',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 29,
            ],
            [
              'name' => 'timezone',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 30,
            ],
            [
              'name' => 'tld',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 31,
            ],
            [
              'name' => 'translation',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 32,
            ],
            [
              'name' => 'un_member',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 33,
            ],
          ],
          'name' => 'alpha',
          'op' => [
            'load' => [
              'name' => 'load',
              'points' => [
                [
                  'args' => [
                    'params' => [
                      [
                        'example' => 'de',
                        'kind' => 'param',
                        'name' => 'id',
                        'orig' => 'code',
                        'reqd' => true,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                    'query' => [
                      [
                        'kind' => 'query',
                        'name' => 'field',
                        'orig' => 'field',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/alpha/{code}',
                  'parts' => [
                    'alpha',
                    '{id}',
                  ],
                  'rename' => [
                    'param' => [
                      'code' => 'id',
                    ],
                  ],
                  'select' => [
                    'exist' => [
                      'field',
                      'id',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'load',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'capital' => [
          'fields' => [
            [
              'name' => 'alt_spelling',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 0,
            ],
            [
              'name' => 'area',
              'req' => false,
              'type' => '`$NUMBER`',
              'active' => true,
              'index$' => 1,
            ],
            [
              'name' => 'border',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 2,
            ],
            [
              'name' => 'capital',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 3,
            ],
            [
              'name' => 'capital_info',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 4,
            ],
            [
              'name' => 'car',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 5,
            ],
            [
              'name' => 'cca2',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 6,
            ],
            [
              'name' => 'cca3',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 7,
            ],
            [
              'name' => 'ccn3',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 8,
            ],
            [
              'name' => 'cioc',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 9,
            ],
            [
              'name' => 'coat_of_arm',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 10,
            ],
            [
              'name' => 'continent',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 11,
            ],
            [
              'name' => 'currency',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 12,
            ],
            [
              'name' => 'demonym',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 13,
            ],
            [
              'name' => 'fifa',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 14,
            ],
            [
              'name' => 'flag',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 15,
            ],
            [
              'name' => 'gini',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 16,
            ],
            [
              'name' => 'idd',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 17,
            ],
            [
              'name' => 'independent',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 18,
            ],
            [
              'name' => 'landlocked',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 19,
            ],
            [
              'name' => 'language',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 20,
            ],
            [
              'name' => 'latlng',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 21,
            ],
            [
              'name' => 'map',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 22,
            ],
            [
              'name' => 'name',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 23,
            ],
            [
              'name' => 'population',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 24,
            ],
            [
              'name' => 'postal_code',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 25,
            ],
            [
              'name' => 'region',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 26,
            ],
            [
              'name' => 'start_of_week',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 27,
            ],
            [
              'name' => 'status',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 28,
            ],
            [
              'name' => 'subregion',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 29,
            ],
            [
              'name' => 'timezone',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 30,
            ],
            [
              'name' => 'tld',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 31,
            ],
            [
              'name' => 'translation',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 32,
            ],
            [
              'name' => 'un_member',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 33,
            ],
          ],
          'name' => 'capital',
          'op' => [
            'load' => [
              'name' => 'load',
              'points' => [
                [
                  'args' => [
                    'params' => [
                      [
                        'example' => 'berlin',
                        'kind' => 'param',
                        'name' => 'id',
                        'orig' => 'capital',
                        'reqd' => true,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                    'query' => [
                      [
                        'kind' => 'query',
                        'name' => 'field',
                        'orig' => 'field',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/capital/{capital}',
                  'parts' => [
                    'capital',
                    '{id}',
                  ],
                  'rename' => [
                    'param' => [
                      'capital' => 'id',
                    ],
                  ],
                  'select' => [
                    'exist' => [
                      'field',
                      'id',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'load',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'name' => [
          'fields' => [
            [
              'name' => 'alt_spelling',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 0,
            ],
            [
              'name' => 'area',
              'req' => false,
              'type' => '`$NUMBER`',
              'active' => true,
              'index$' => 1,
            ],
            [
              'name' => 'border',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 2,
            ],
            [
              'name' => 'capital',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 3,
            ],
            [
              'name' => 'capital_info',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 4,
            ],
            [
              'name' => 'car',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 5,
            ],
            [
              'name' => 'cca2',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 6,
            ],
            [
              'name' => 'cca3',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 7,
            ],
            [
              'name' => 'ccn3',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 8,
            ],
            [
              'name' => 'cioc',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 9,
            ],
            [
              'name' => 'coat_of_arm',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 10,
            ],
            [
              'name' => 'continent',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 11,
            ],
            [
              'name' => 'currency',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 12,
            ],
            [
              'name' => 'demonym',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 13,
            ],
            [
              'name' => 'fifa',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 14,
            ],
            [
              'name' => 'flag',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 15,
            ],
            [
              'name' => 'gini',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 16,
            ],
            [
              'name' => 'idd',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 17,
            ],
            [
              'name' => 'independent',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 18,
            ],
            [
              'name' => 'landlocked',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 19,
            ],
            [
              'name' => 'language',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 20,
            ],
            [
              'name' => 'latlng',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 21,
            ],
            [
              'name' => 'map',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 22,
            ],
            [
              'name' => 'name',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 23,
            ],
            [
              'name' => 'population',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 24,
            ],
            [
              'name' => 'postal_code',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 25,
            ],
            [
              'name' => 'region',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 26,
            ],
            [
              'name' => 'start_of_week',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 27,
            ],
            [
              'name' => 'status',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 28,
            ],
            [
              'name' => 'subregion',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 29,
            ],
            [
              'name' => 'timezone',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 30,
            ],
            [
              'name' => 'tld',
              'req' => false,
              'type' => '`$ARRAY`',
              'active' => true,
              'index$' => 31,
            ],
            [
              'name' => 'translation',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 32,
            ],
            [
              'name' => 'un_member',
              'req' => false,
              'type' => '`$BOOLEAN`',
              'active' => true,
              'index$' => 33,
            ],
          ],
          'name' => 'name',
          'op' => [
            'load' => [
              'name' => 'load',
              'points' => [
                [
                  'args' => [
                    'params' => [
                      [
                        'example' => 'germany',
                        'kind' => 'param',
                        'name' => 'id',
                        'orig' => 'name',
                        'reqd' => true,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                    'query' => [
                      [
                        'kind' => 'query',
                        'name' => 'field',
                        'orig' => 'field',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => false,
                        'kind' => 'query',
                        'name' => 'full_text',
                        'orig' => 'full_text',
                        'reqd' => false,
                        'type' => '`$BOOLEAN`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/name/{name}',
                  'parts' => [
                    'name',
                    '{id}',
                  ],
                  'rename' => [
                    'param' => [
                      'name' => 'id',
                    ],
                  ],
                  'select' => [
                    'exist' => [
                      'field',
                      'full_text',
                      'id',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'load',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
      ],
        ];
    }


    public static function make_feature(string $name)
    {
        require_once __DIR__ . '/features.php';
        return RestCountriesFeatures::make_feature($name);
    }
}
